export const socialLinks = [
  {
    label: "INSTAGRAM",
    color: "bg-purple-500",
    href: "https://www.instagram.com/omgitsretrograde/",
  },
  {
    label: "SPOTIFY",
    color: "bg-green-500",
    href: "https://open.spotify.com/artist/1nf07RPZDd3E5LRg64vV61",
  },
  {
    label: "BOOK TABLE",
    color: "bg-magenta text-white",
    href: "https://www.google.com/maps/place/Retrograde+Coffee+-+Gulberg/@31.5200515,74.3463278,17z/data=!3m1!4b1!4m6!3m5!1s0x3919055116e42c0d:0xfed728ebcf47be89!8m2!3d31.520047!4d74.3489027!16s%2Fg%2F11n3kztsrs?entry=ttu&g_ep=EgoyMDI2MDMxOC4xIKXMDSoASAFQAw%3D%3D",
  },
];

export const stats = [
  { label: "DAILY CUPS", value: "1,984", valueColor: "text-magenta" },
  { label: "VINYL SPINS", value: "402", valueColor: "text-ink" },
  { label: "ARCADE", value: "9,008", valueColor: "text-ink" },
  { label: "COMBO RATE", value: "87%", valueColor: "text-ink" },
];

export interface MenuItem {
  id: string;
  category: string;
  title: string;
  color: string;
  price: string;
  titleColor: string;
  description: string;
}

export const menuItems: MenuItem[] = [
  {
    id: "crt-mocha",
    category: "SIGNATURE",
    title: "CRT MOCHA",
    color: "bg-cyan",
    price: "¥720",
    titleColor: "text-magenta",
    description: "Dark roast, milk foam, bitter cocoa, neon cherry dust.",
  },
  {
    id: "manga-fizz",
    category: "COLD BREW",
    title: "MANGA FIZZ",
    color: "bg-magenta",
    price: "¥640",
    titleColor: "text-ink",
    description: "Yuzu tonic, cold brew base, crackling citrus top note.",
  },
  {
    id: "byte-waffle",
    category: "DESSERT",
    title: "BYTE WAFFLE",
    color: "bg-white",
    price: "¥580",
    titleColor: "text-ink",
    description: "Grid-pressed waffle, vanilla whip, pixel berry jam.",
  },
  {
    id: "cassette-latte",
    category: "ESPRESSO",
    title: "CASSETTE LATTE",
    color: "bg-cyan",
    price: "¥610",
    titleColor: "text-magenta",
    description: "Double shot espresso, silky milk, caramel ripple finish.",
  },
  {
    id: "neon-americano",
    category: "ESPRESSO",
    title: "NEON AMERICANO",
    color: "bg-white",
    price: "¥520",
    titleColor: "text-ink",
    description: "Long black pull with bright citrus and cocoa aroma.",
  },
  {
    id: "arcade-cappuccino",
    category: "ESPRESSO",
    title: "ARCADE CAPPUCCINO",
    color: "bg-magenta",
    price: "¥590",
    titleColor: "text-ink",
    description: "Classic cap with dense foam and toasted hazelnut notes.",
  },
  {
    id: "pixel-flat-white",
    category: "ESPRESSO",
    title: "PIXEL FLAT WHITE",
    color: "bg-white",
    price: "¥600",
    titleColor: "text-magenta",
    description: "Ristretto base, velvety microfoam, chocolate biscuit.",
  },
  {
    id: "vhs-cortado",
    category: "ESPRESSO",
    title: "VHS CORTADO",
    color: "bg-magenta",
    price: "¥560",
    titleColor: "text-ink",
    description: "Equal parts espresso and steamed milk, smooth.",
  },
  {
    id: "vinyl-espresso",
    category: "ESPRESSO",
    title: "VINYL ESPRESSO",
    color: "bg-cyan",
    price: "¥420",
    titleColor: "text-ink",
    description: "Straight shot with syrupy body and dark chocolate edge.",
  },
  {
    id: "synth-cold-brew",
    category: "COLD BREW",
    title: "SYNTH COLD BREW",
    color: "bg-yellow",
    price: "¥620",
    titleColor: "text-magenta",
    description: "18-hour steep with smooth body and subtle sweet finish.",
  },
  {
    id: "glitch-tonic",
    category: "COLD BREW",
    title: "GLITCH TONIC",
    color: "bg-magenta",
    price: "¥650",
    titleColor: "text-ink",
    description: "Cold brew, tonic sparkle, lime zest and mint perfume.",
  },
  {
    id: "midnight-iced-latte",
    category: "COLD BREW",
    title: "MIDNIGHT ICED LATTE",
    color: "bg-cyan",
    price: "¥630",
    titleColor: "text-ink",
    description: "Chilled espresso, whole milk, vanilla bean and ice.",
  },
  {
    id: "yuzu-drip",
    category: "FILTER",
    title: "YUZU DRIP",
    color: "bg-white",
    price: "¥690",
    titleColor: "text-magenta",
    description: "Hand-poured single origin with bright yuzu-like acidity.",
  },
  {
    id: "sunset-v60",
    category: "FILTER",
    title: "SUNSET V60",
    color: "bg-magenta",
    price: "¥710",
    titleColor: "text-ink",
    description: "Clean cup profile, stone fruit sweetness, tea-like finish.",
  },
  {
    id: "city-kalita",
    category: "FILTER",
    title: "CITY KALITA",
    color: "bg-yellow",
    price: "¥700",
    titleColor: "text-ink",
    description: "Balanced body with brown sugar and citrus marmalade.",
  },
  {
    id: "cloud-matcha",
    category: "NON-COFFEE",
    title: "CLOUD MATCHA",
    color: "bg-white",
    price: "¥670",
    titleColor: "text-magenta",
    description: "Matcha whisked with oat milk and honey foam.",
  },
  {
    id: "strawberry-soda",
    category: "NON-COFFEE",
    title: "STRAWBERRY SODA",
    color: "bg-cyan",
    price: "¥540",
    titleColor: "text-ink",
    description: "House strawberry syrup, sparkling water, fresh basil hint.",
  },
  {
    id: "ginger-lemonade",
    category: "NON-COFFEE",
    title: "GINGER LEMONADE",
    color: "bg-magenta",
    price: "¥500",
    titleColor: "text-ink",
    description: "Fresh lemon juice, ginger kick, light syrup and soda.",
  },
  {
    id: "starlight-chai",
    category: "NON-COFFEE",
    title: "STARLIGHT CHAI",
    color: "bg-white",
    price: "¥560",
    titleColor: "text-magenta",
    description: "Spiced black tea simmered with milk and brown sugar.",
  },
  {
    id: "retro-brownie",
    category: "DESSERT",
    title: "RETRO BROWNIE",
    color: "bg-cyan",
    price: "¥460",
    titleColor: "text-ink",
    description: "Fudgy brownie square with toasted walnut and sea salt.",
  },
  {
    id: "pixel-cheesecake",
    category: "DESSERT",
    title: "PIXEL CHEESECAKE",
    color: "bg-magenta",
    price: "¥620",
    titleColor: "text-ink",
    description: "Baked vanilla cheesecake with berry coulis and crumbs.",
  },
  {
    id: "anime-tiramisu",
    category: "DESSERT",
    title: "ANIME TIRAMISU",
    color: "bg-white",
    price: "¥640",
    titleColor: "text-magenta",
    description: "Espresso-soaked sponge, mascarpone cream, cocoa.",
  },
  {
    id: "caramel-choux",
    category: "DESSERT",
    title: "CARAMEL CHOUX",
    color: "bg-yellow",
    price: "¥520",
    titleColor: "text-ink",
    description: "Crisp choux bun filled with caramel cream and praline.",
  },
  {
    id: "butter-croissant",
    category: "BAKERY",
    title: "BUTTER CROISSANT",
    color: "bg-magenta",
    price: "¥390",
    titleColor: "text-ink",
    description: "Flaky laminated pastry baked fresh with French butter.",
  },
  {
    id: "almond-danish",
    category: "BAKERY",
    title: "ALMOND DANISH",
    color: "bg-yellow",
    price: "¥430",
    titleColor: "text-magenta",
    description: "Sweet pastry with almond cream, toasted slices, glaze.",
  },
  {
    id: "choco-chip-cookie",
    category: "BAKERY",
    title: "CHOCO CHIP COOKIE",
    color: "bg-white",
    price: "¥340",
    titleColor: "text-ink",
    description: "Soft-center cookie with dark chocolate chunks and salt.",
  },
  {
    id: "umami-sando",
    category: "SAVORY",
    title: "UMAMI SANDO",
    color: "bg-cyan",
    price: "¥720",
    titleColor: "text-ink",
    description: "Toasted milk bread sandwich, egg mayo, pickled onions.",
  },
  {
    id: "tokyo-toast",
    category: "SAVORY",
    title: "TOKYO TOAST",
    color: "bg-yellow",
    price: "¥680",
    titleColor: "text-magenta",
    description: "Thick toast, whipped ricotta, tomatoes, basil oil drizzle.",
  },
  {
    id: "ramen-egg-muffin",
    category: "SAVORY",
    title: "RAMEN EGG MUFFIN",
    color: "bg-white",
    price: "¥690",
    titleColor: "text-ink",
    description: "English muffin, soft egg, chili jam, melted cheddar.",
  },
  {
    id: "honey-oat-bowl",
    category: "BREAKFAST",
    title: "HONEY OAT BOWL",
    color: "bg-magenta",
    price: "¥610",
    titleColor: "text-ink",
    description: "Warm oats, seasonal fruit, toasted seeds, wildflower.",
  },
];
